#!/bin/bash


IMAGE=/tmp/i3lock.png
SCREENSHOT="scrot -z  $IMAGE"

#Blur Types

#BLURTYPE="0x5"
#BLURTYPE="0x2"
#BLURTYPE="5x2"
BLURTYPE="2x8"
#BLURTYPE="2x3"


$SCREENSHOT
convert $IMAGE -blur $BLURTYPE $IMAGE
i3lock -i $IMAGE
rm $IMAGE
